### ISSUE TITLE
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed

### ISSUE THREAD

**Issue by anicolson** [ECOFRI/CXR_LLaVA#4]
Hi, I am getting the following error with transformers.AutoModel.from_pretrained("ECOFRI/CXR-LLAVA-v2", trust_remote_code=True):

    model = transformers.AutoModel.from_pretrained("ECOFRI/CXR-LLAVA-v2", trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/cxrmate2-virga-venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 557, in from_pretrained
    cls.register(config.__class__, model_class, exist_ok=True)
  File "/scratch3/nic261/environments/cxrmate2-virga-venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 583, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers_modules.ECOFRI.CXR-LLAVA-v2.b2224786bb90d54b1e1291171866706cfbb44e2b.CXR_LLAVA_HF.CXRLLAVAConfig'> and you passed <class 'transformers_modules.ECOFRI.CXR-LLAVA-v2.b2224786bb90d54b1e1291171866706cfbb44e2b.CXR_LLAVA_HF.CXRLLAVAConfig'>. Fix one of those so they match!

**Comment by ECOFRI** [comment]
I recently set up a new Python virtual environment and successfully tested loading the model and generating radiologic reports without any issues.

The environment I used is as follows:

- Python 3.10.10
- Torch 2.3.0+cu118
- Transformers 4.41.1
- Sentencepiece 0.2.0
- CUDA-based Windows environment

Since I couldn't reproduce the issue, I'm unable to provide a precise solution at this time. 

However, if you can share details about your execution environment, including the version of the Transformers library you're using, I might be able to assist you further.

**Comment by anicolson** [comment]
Thanks ECOFRI, it was the transformers version
